# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Generate cache key
          command: ./bash/checksum.sh > /tmp/checksum.txt

      - restore_cache:
          keys:
          - node-dependencies-{{ checksum "/tmp/checksum.txt" }}

      - run:
          name: Install dependencies
          command: |
            yarn run install-all

      - save_cache:
          key: node-dependencies-{{ checksum "/tmp/checksum.txt" }}
          paths:
            - node_modules
            - pkg/api/node_modules
            - pkg/fe/node_modules

      - run:
          name: Run tests
          command: |
            yarn run test

      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get -y -qq install awscli

      - run:
          name: Deploy
          command: |
            yarn run deploy
